# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := action_after_build
### Generated for copy rule.
/Users/saadkhurshid/Desktop/c11workspace/firetext/node-audio/x64/audio.node: TOOLSET := $(TOOLSET)
/Users/saadkhurshid/Desktop/c11workspace/firetext/node-audio/x64/audio.node: $(builddir)/audio.node FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += /Users/saadkhurshid/Desktop/c11workspace/firetext/node-audio/x64/audio.node
/Users/saadkhurshid/Desktop/c11workspace/firetext/node-audio/x64/webm.dylib: TOOLSET := $(TOOLSET)
/Users/saadkhurshid/Desktop/c11workspace/firetext/node-audio/x64/webm.dylib: $(builddir)/webm.dylib FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += /Users/saadkhurshid/Desktop/c11workspace/firetext/node-audio/x64/webm.dylib
binding_gyp_action_after_build_target_copies = /Users/saadkhurshid/Desktop/c11workspace/firetext/node-audio/x64/audio.node /Users/saadkhurshid/Desktop/c11workspace/firetext/node-audio/x64/webm.dylib

### Rules for final target.
# Build our special outputs first.
$(obj).target/action_after_build.stamp: | $(binding_gyp_action_after_build_target_copies)

# Preserve order dependency of special output on deps.
$(binding_gyp_action_after_build_target_copies): | $(builddir)/audio.node $(builddir)/webm.dylib

$(obj).target/action_after_build.stamp: TOOLSET := $(TOOLSET)
$(obj).target/action_after_build.stamp: $(builddir)/audio.node $(builddir)/webm.dylib FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/action_after_build.stamp
# Add target alias
.PHONY: action_after_build
action_after_build: $(obj).target/action_after_build.stamp

# Add target alias to "all" target.
.PHONY: all
all: action_after_build

