# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := webm
DEFS_Debug := \
	'-DNODE_GYP_MODULE_NAME=webm' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-DV8_IMMINENT_DEPRECATION_WARNINGS' \
	'-D_GLIBCXX_USE_CXX11_ABI=1' \
	'-D_DARWIN_USE_64_BIT_INODE=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DOPENSSL_NO_PINSHARED' \
	'-DOPENSSL_THREADS' \
	'-D__MACOSX_CORE__' \
	'-DDEBUG' \
	'-D_DEBUG' \
	'-DV8_ENABLE_CHECKS'

# Flags passed to all source files.
CFLAGS_Debug := \
	-O0 \
	-gdwarf-2 \
	-mmacosx-version-min=10.13 \
	-arch x86_64 \
	-Wall \
	-Wendif-labels \
	-W \
	-Wno-unused-parameter

# Flags passed to only C files.
CFLAGS_C_Debug := \
	-fno-strict-aliasing

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-std=gnu++14 \
	-stdlib=libc++ \
	-fno-rtti \
	-fno-strict-aliasing

# Flags passed to only ObjC files.
CFLAGS_OBJC_Debug :=

# Flags passed to only ObjC++ files.
CFLAGS_OBJCC_Debug :=

INCS_Debug := \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/include/node \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/src \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/deps/openssl/config \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/deps/openssl/openssl/include \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/deps/uv/include \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/deps/zlib \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/deps/v8/include \
	-IC:\Users\ztech.pk\Desktop\libwebm

DEFS_Release := \
	'-DNODE_GYP_MODULE_NAME=webm' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-DV8_DEPRECATION_WARNINGS' \
	'-DV8_IMMINENT_DEPRECATION_WARNINGS' \
	'-D_GLIBCXX_USE_CXX11_ABI=1' \
	'-D_DARWIN_USE_64_BIT_INODE=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DOPENSSL_NO_PINSHARED' \
	'-DOPENSSL_THREADS' \
	'-D__MACOSX_CORE__'

# Flags passed to all source files.
CFLAGS_Release := \
	-O3 \
	-gdwarf-2 \
	-mmacosx-version-min=10.13 \
	-arch x86_64 \
	-Wall \
	-Wendif-labels \
	-W \
	-Wno-unused-parameter

# Flags passed to only C files.
CFLAGS_C_Release := \
	-fno-strict-aliasing

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-std=gnu++14 \
	-stdlib=libc++ \
	-fno-rtti \
	-fno-strict-aliasing

# Flags passed to only ObjC files.
CFLAGS_OBJC_Release :=

# Flags passed to only ObjC++ files.
CFLAGS_OBJCC_Release :=

INCS_Release := \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/include/node \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/src \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/deps/openssl/config \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/deps/openssl/openssl/include \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/deps/uv/include \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/deps/zlib \
	-I/Users/saadkhurshid/Library/Caches/node-gyp/16.20.2/deps/v8/include \
	-IC:\Users\ztech.pk\Desktop\libwebm

OBJS := \
	$(obj).target/$(TARGET)/webvtt/vttreader.o \
	$(obj).target/$(TARGET)/webvtt/webvttparser.o \
	$(obj).target/$(TARGET)/webm_muxer.o \
	$(obj).target/$(TARGET)/sample_muxer_metadata.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))
$(OBJS): GYP_OBJCFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(CFLAGS_OBJC_$(BUILDTYPE))
$(OBJS): GYP_OBJCXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(CFLAGS_OBJCC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-search_paths_first \
	-mmacosx-version-min=10.13 \
	-arch x86_64 \
	-L$(builddir) \
	-install_name @rpath/webm.dylib \
	-stdlib=libc++

LIBTOOLFLAGS_Debug := \
	-Wl,-search_paths_first

LDFLAGS_Release := \
	-Wl,-search_paths_first \
	-mmacosx-version-min=10.13 \
	-arch x86_64 \
	-L$(builddir) \
	-install_name @rpath/webm.dylib \
	-stdlib=libc++

LIBTOOLFLAGS_Release := \
	-Wl,-search_paths_first

LIBS := \
	-lwebm \
	-LC:\Users\ztech.pk\Desktop\libwebm

$(builddir)/webm.dylib: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/webm.dylib: LIBS := $(LIBS)
$(builddir)/webm.dylib: GYP_LIBTOOLFLAGS := $(LIBTOOLFLAGS_$(BUILDTYPE))
$(builddir)/webm.dylib: LD_INPUTS := $(OBJS)
$(builddir)/webm.dylib: TOOLSET := $(TOOLSET)
$(builddir)/webm.dylib: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,solink)

all_deps += $(builddir)/webm.dylib
# Add target alias
.PHONY: webm
webm: $(builddir)/webm.dylib

# Short alias for building this shared library.
.PHONY: webm.dylib
webm.dylib: $(builddir)/webm.dylib

# Add shared library to "all" target.
.PHONY: all
all: $(builddir)/webm.dylib

